om_site_settings.site_settings:
  type: config_object
  label: Site Settings
  mapping:
    archive_length:
      type: number
      label: Archive Length
    website_code:
      type: string
      label: Website Code
    website_description:
      type: text_format
      label: Website Description
