om_site_settings:
  path: 'admin/config/site-settings'
  defaults:
    _title: 'Site Settings'
    _form: 'Drupal\om_site_settings\Form\OmSettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE
om_site_settings.site_settings:
  path: '/om-site-settings'
  defaults:
    _title: 'Site Settings'
    _controller: '\Drupal\om_site_settings\Controller\OmSiteSettingsController::build'
  requirements:
    _permission: 'access content'
