om_site_settings:
  path: 'admin/config/site-settings'
  defaults:
    _title: 'Site Settings'
    _form: 'Drupal\om_site_settings\Form\OmSettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE